# Generated by Django 4.2.2 on 2023-09-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Hora')),
                ('descripcion', models.TextField()),
                ('id_personal', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='personal.personal')),
            ],
        ),
    ]
