# Generated by Django 4.2.2 on 2023-09-13 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnado', '0004_delete_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fechaA', models.DateField()),
                ('horaA', models.TimeField(auto_now=True)),
                ('condicion', models.CharField(blank=True, max_length=20)),
                ('cantidadA', models.CharField(blank=True, max_length=3)),
                ('turno', models.CharField(blank=True, max_length=30)),
                ('reintegrado', models.CharField(blank=True, max_length=30)),
                ('evento', models.CharField(blank=True, max_length=30)),
                ('id_alumno', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='alumnado.alumno')),
            ],
        ),
    ]
