# Generated by Django 4.2.2 on 2023-09-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='horaA',
            field=models.TimeField(),
        ),
    ]
