# Generated by Django 4.2.2 on 2023-09-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='cantidadA',
            field=models.CharField(blank=True, max_length=3, verbose_name='Cantidad de Inasistencias'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='condicion',
            field=models.IntegerField(choices=[[0, 'Regultar'], [1, 'Semipresencial'], [2, 'Libre']], verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fechaA',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='horaA',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='reintegrado',
            field=models.BooleanField(default=False, verbose_name='Reintegrado'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='turno',
            field=models.CharField(blank=True, max_length=30, verbose_name='Turno'),
        ),
    ]
