# Generated by Django 4.2.2 on 2023-10-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_asistencia_cantidada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='condicion',
            field=models.IntegerField(choices=[[0, 'Regular'], [1, 'Semipresencial'], [2, 'Libre']], verbose_name='Condición'),
        ),
    ]
