# Generated by Django 4.2.2 on 2023-09-22 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialidad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
