# Generated by Django 4.2.2 on 2023-09-23 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('dni_p', models.CharField(max_length=9)),
                ('cuil_p', models.CharField(max_length=15)),
                ('apellido_p', models.CharField(max_length=50)),
                ('nombre_p', models.CharField(max_length=50)),
                ('legajo_p', models.CharField(max_length=10)),
                ('telefono_p', models.CharField(blank=True, max_length=20)),
                ('direccion_p', models.CharField(blank=True, max_length=50)),
                ('fecha_nac_p', models.DateField()),
                ('copiaDNI_p', models.ImageField(blank=True, upload_to='personal/images/')),
                ('rol_p', models.CharField(blank=True, max_length=50)),
                ('id_materia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='materia.materia')),
            ],
        ),
    ]
