# Generated by Django 4.2.2 on 2023-09-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnado', '0003_asistencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
