# Generated by Django 4.2.2 on 2023-09-23 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_remove_curso_nombrecurso'),
        ('alumnado', '0004_delete_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='id_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
    ]
