# Generated by Django 4.2.2 on 2023-10-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnado', '0005_alumno_id_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cuil_a',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
