# Generated by Django 4.2.2 on 2023-10-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnado', '0006_alter_alumno_cuil_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nac',
            field=models.DateField(blank=True),
        ),
    ]
