# Generated by Django 4.2.2 on 2023-10-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnado', '0007_alter_alumno_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='copiaDNI_A',
            field=models.ImageField(blank=True, null=True, upload_to='alumnado/images/'),
        ),
    ]
