# Generated by Django 4.2.2 on 2023-10-19 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alter_curso_id_materia'),
        ('alumnado', '0008_alter_alumno_copiadni_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='copiaDNI_A',
            field=models.ImageField(blank=True, upload_to='alumnado/images/'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cuil_a',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_curso',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
    ]
