# Generated by Django 4.2.2 on 2023-10-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnado', '0009_alter_alumno_copiadni_a_alter_alumno_cuil_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='copiaDNI_A',
            field=models.ImageField(blank=True, null=True, upload_to='alumnado/images/'),
        ),
    ]
