# Generated by Django 4.2.2 on 2023-10-19 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alter_curso_id_materia'),
        ('alumnado', '0010_alter_alumno_copiadni_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tutores',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
