# Generated by Django 4.2.2 on 2023-09-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('Annio', models.CharField(max_length=5)),
                ('Division', models.CharField(max_length=4)),
            ],
        ),
    ]
