# Generated by Django 4.2.2 on 2023-09-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombreCurso',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
