# Generated by Django 4.2.2 on 2023-09-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_nombrecurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nombreCurso',
        ),
    ]
