# Generated by Django 4.2.2 on 2023-10-11 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
        ('curso', '0004_curso_id_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materia.materia'),
        ),
    ]
