# Generated by Django 4.2.2 on 2023-09-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('dni_p', models.CharField(max_length=9)),
                ('cuil_p', models.CharField(max_length=15)),
                ('apellido_p', models.CharField(max_length=50)),
                ('nombre_p', models.CharField(max_length=50)),
                ('legajo', models.CharField(max_length=10)),
                ('telefono_p', models.CharField(blank=True, max_length=20)),
                ('direccion_p', models.CharField(blank=True, max_length=50)),
                ('fecha_nac_p', models.DateField()),
                ('copiaDNI_p', models.ImageField(blank=True, upload_to='alumnado/images/')),
                ('rol_p', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
