# Generated by Django 4.2.2 on 2023-09-23 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidad', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=50)),
                ('id_especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='especialidad.especialidad')),
            ],
        ),
    ]
